name: 值班提醒
on:
  schedule:
    - cron: "0 9 * * 1"  # 每周一早上9点运行
  workflow_dispatch:  # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行脚本
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}  # 从 GitHub Secrets 中获取
        run: |
          python pai_ban.py
